version: '3'

services:
  converter:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 8
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./static:/app/static
      - ./fonts:/app/fonts
    restart: always